services:
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "5001"

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    expose:
      - "80"

  nginx:
    build: ./nginx
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
