version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "5173:80"
