services:
  backend:
    build: ./backend
    container_name: backend_container
    networks:
      - app-net
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "5001"

  frontend:
    build: ./frontend
    container_name: frontend_container
    networks:
      - app-net
    restart: always
    expose:
      - "80"

  nginx:
    build: ./nginx
    container_name: nginx_container
    networks:
      - app-net
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email your@email.com
      --agree-tos
      --no-eff-email
      -d funtogether.online -d www.funtogether.online"

networks:
  app-net:
